### ISSUE TITLE
Astro template doesn't get copied

### ISSUE THREAD

**Issue by heysujal** [vinitshahdeo/portfolio#3]
When trying to create a copy of the template using the command given in readme, the program fails after initializing the Astro project. None of the files of template get copied.
`npm create astro@latest -- --template vinitshahdeo/portfolio`

![image](https://github.com/user-attachments/assets/b897cf8c-d81c-47ce-a0ad-0900de459ca1)

**Comment by vinitshahdeo** [comment]
Hello @heysujal!
Thanks for reporting this. Which Node version are you using? 

Can you please try installing with Node >20?

```js
"engines": {
    "node": ">=20.0.0"
  },
```

> This template requires Node 20 or higher.

<img width="499" alt="Screenshot 2024-08-04 at 12 14 18 PM" src="https://github.com/user-attachments/assets/7e0a1838-082a-40a5-8b8a-2e3b98c6b7eb">

**Comment by heysujal** [comment]
Oh, I was using older node version
